---
title: "Day 1: Advanced Data Visualization with R"
author: "Emi Tanaka"
date: "8th December 2021"
---

## Slides

We recommend that you open the html slides <i class="fas fa-link"></i> with [Google Chrome web browser](https://www.google.com/intl/en_au/chrome/). 

0. Getting started [<i class="fas fa-link"></i>](slides/day1-session0.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session0.pdf)
1. R Graphics using `grid` [<i class="fas fa-link"></i>](slides/day1-session1.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session1.pdf)
2. `ggplot2` internals [<i class="fas fa-link"></i>](slides/day1-session2.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session2.pdf)
3. Writing `ggplot2` extensions [<i class="fas fa-link"></i>](slides/day1-session3.html) [<i class="fas fa-file-pdf"></i>](slides/day1-session3.pdf)


## Schedule

Time | Activity 
:----|:---
8.45-9.00 | Registration + Installation Help
9.00-9.45 | **Lesson 1:** Getting started & R Graphics using `grid`
9.45-10.00 |  *Break*
10.00-10.45 | **Lesson 2:**  `ggplot2` internals
10.45-11.00 |  *Break*
11.00-11.45 | **Lesson 3:** Writing `ggplot2` extensions
11.45-12.00 |  *Break*


## Exercises

Before getting started, you will need to install the following R-packages:

```r
```{r, echo = FALSE, results='asis'}
pkgs <- readLines("install-pkgs-day1.txt")
pkgsq <- paste0("'", pkgs, "'")
glue::glue("
  install.packages(c( {paste0(pkgsq, collapse=',\\n\\t\\t\\t\\t\\t')}))
  ")
```
```

1. Drawing with `grid` <a class="tag" href="exercises/day1-exercise-01.Rmd" download><i class="fas fa-download"></i> Rmd</a> <a class="tag" href="exercises/day1-exercise-01.html" target="_blank"><i class="fas fa-globe"></i> html</a> <a class="tag" href="exercises/day1-exercise-01-solution.Rmd" download><i class="fas fa-download"></i> solution Rmd</a> <a class="tag" href="exercises/day1-exercise-01-solution.html" target="_blank"><i class="fas fa-globe"></i> html solution</a>

2. Harnessing `grid` on `ggplot2` outputs <a class="tag" href="exercises/day1-exercise-02.Rmd" download><i class="fas fa-download"></i> Rmd</a> <a class="tag" href="exercises/day1-exercise-02.html" target="_blank"><i class="fas fa-globe"></i> html</a> <a class="tag" href="exercises/day1-exercise-02-solution.Rmd" download><i class="fas fa-download"></i> solution Rmd</a> <a class="tag" href="exercises/day1-exercise-02-solution.html" target="_blank"><i class="fas fa-globe"></i> html solution</a>


3. DIY `ggplot2` extension <a class="tag" href="exercises/day1-exercise-03.Rmd" download><i class="fas fa-download"></i> Rmd</a> <a class="tag" href="exercises/day1-exercise-03.html" target="_blank"><i class="fas fa-globe"></i> html</a> <a class="tag" href="exercises/day1-exercise-03-solution.Rmd" download><i class="fas fa-download"></i> solution Rmd</a> <a class="tag" href="exercises/day1-exercise-03-solution.html" target="_blank"><i class="fas fa-globe"></i> html solution</a>


